import type { Metadata } from "next";
import "./globals.css";

import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      style={{backgroundColor: '#0f0715'}} 
      className={`${inter.className}  dark flex items-center flex-col relative custom-background backdrop-blur-sm`}
      >
        {children}
      </body>
    </html>
  );
}
